# Filament Tutorial

#### This tutorial serves as a tour of the filament.py package and shows what sort of methods are at your disposal from the Filament Class. 

You do not need to import both filament_functions and Filament. If you need one or two functions and have a set data set you are working with already processed, you can just use filament_functions. But if you have a raw DisPerSE skeleton file and want to start working from there, importing the Filament class might be the best option (and highly recommended). Because this is a class, all of the functions (methods) that pertain to filaments are encapsulated together and more modular. 

In [1]:
#Begin with import the package 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import filament_functions as fils   # imports filament functions
from filament import Filament       # imports Filament class inside the "filament" module - which contains most of the filament functions as methods 

In [2]:
# Sample path to GAMA filaments 
path_to_skel = '../DataFiles/curved_slice1_final.BRK.a.NDskl'

In [3]:
# Whenever Filament is called, the path to your .NDskl skeleton file has to be provided in the argument
#help(Filament.__init__)

#### Importing filament skeleton files

In [4]:
# For importing filaments
#help(Filament.import_fils)

In [5]:
# Import filaments with skeleton file (example here is an instance call of the class, but we did not assign a variable to this instance)
#Filament(path_to_skel,'2D').import_fils()

In [6]:
# Best way to call Filament class is to assign a variable to an instance of your class with your path to a skeleton file
my_filaments = Filament(path_to_skel,'2D')
myfils = my_filaments.import_fils()     # then use methods with the above instance variable! 

header1, ANDSKEL

ndims, 2

Comments, #No comments (RB)

Bounding box, BBOX [-10.1604,-10.1295] [20.3587,20.3195]

ncrit, 104
nfils, 73
Reading data fields:
CP field: persistence_ratio

CP field: persistence_nsigmas

CP field: persistence

CP field: persistence_pair

CP field: parent_index

CP field: parent_log_index

CP field: log_field_value

CP field: field_value

CP field: cell

Filament field: field_value

Filament field: orientation

Filament field: cell

Filament field: log_field_value

Filament field: type

Reading filaments took 0.00 secs.
header1, ANDSKEL

ndims, 2

Comments, #No comments (RB)

Bounding box, BBOX [-10.1604,-10.1295] [20.3587,20.3195]

ncrit, 104
nfils, 73
Reading data fields:
CP field: persistence_ratio

CP field: persistence_nsigmas

CP field: persistence

CP field: persistence_pair

CP field: parent_index

CP field: parent_log_index

CP field: log_field_value

CP field: field_value

CP field: cell

Filament field: field_value

Filament field: orientation

F

#### Working with filament dictionary

In [7]:
# Use this variable if you want to work with the entire dictionary on your own without methods
#myfils

In [8]:
# From here we can slice the dictionary returned to get information of interest
#myfils['filaments']     # coordinates of filaments and their sub segments:

##### Small side note

Notice that to use class methods we only use the first instance of the class call where we pass the path to skeleton (my_filaments), NOT myfils!
The reason for this is a little complicated [explain?] but has to do with the \__init__ method in the Filament class and instances (ie. myfils saves the instance and data structure of using .import_fils() whereas Filament(path) only prints the import after running the method, but does NOT save the instance, which is why calling my_filaments just gives the instance memory location [shown below]).


In [9]:
# Calling this will only give memory location - but to use useful methods we use this variable followed be ".method_of_interest()"
my_filaments

#### Obtaining critical points from the dictionary 

https://www2.iap.fr/users/sousbie/web/html/index3333.html?category/Skeleton-I-O

In [10]:
# This method is used internally to obtain the critical points based on what type you'd like to slice from the dictionary
#help(my_filaments.get_cp)

In [11]:
#help(my_filaments.saddles)

In [12]:
# To get all nodes in the dictionary - the values here following the DisPerSE NDskl_ascii format (linked above)
my_filaments.saddles()

[{'cp_idx': 2.0,
  'px': 2.35974,
  'py': 2.84685,
  'pair_ID': 9.0,
  'boundary': 0.0,
  'nfil': 1,
  'destID,filID': [[10, 4]],
  'Field Vals': [86.7249,
   3.125655,
   2149.081,
   9.0,
   6.0,
   6.0,
   3.33729,
   2174.15,
   14.0]},
 {'cp_idx': 2.0,
  'px': -0.635279,
  'py': -5.40593,
  'pair_ID': 1.0,
  'boundary': 0.0,
  'nfil': 1,
  'destID,filID': [[23, 20]],
  'Field Vals': [-1.0,
   -1.0,
   1.797693e+308,
   1.0,
   -1.0,
   -1.0,
   3.476421,
   2995.17,
   1109.0]},
 {'cp_idx': 2.0,
  'px': 1.325,
  'py': -2.20819,
  'pair_ID': 10.0,
  'boundary': 0.0,
  'nfil': 1,
  'destID,filID': [[21, 18]],
  'Field Vals': [81.80694,
   3.089764,
   1933.888,
   10.0,
   1.0,
   1.0,
   3.291773,
   1957.82,
   1165.0]},
 {'cp_idx': 2.0,
  'px': 6.38872,
  'py': -0.487649,
  'pair_ID': 8.0,
  'boundary': 0.0,
  'nfil': 1,
  'destID,filID': [[15, 10]],
  'Field Vals': [74.95454,
   3.035882,
   1761.205,
   8.0,
   6.0,
   6.0,
   3.251643,
   1785.02,
   1479.0]},
 {'cp_idx': 2.0,

In [13]:
# Get just the node coordinates for each node 
my_filaments.saddle_coordinates()

array([[ 2.35974 ,  2.84685 ],
       [-0.635279, -5.40593 ],
       [ 1.325   , -2.20819 ],
       [ 6.38872 , -0.487649],
       [-5.46421 ,  7.32519 ],
       [ 9.95433 ,  9.85085 ],
       [ 4.14438 , -1.621   ]])

In [14]:
# This applies to all critical point types
print(my_filaments.voids(), "\n", my_filaments.walls(), "\n", my_filaments.saddles(), "\n", my_filaments.nodes(), my_filaments.bifurcation_points())

[{'cp_idx': 0.0, 'px': -2.5954, 'py': -6.5046, 'pair_ID': 11.0, 'boundary': 0.0, 'nfil': 0, 'destID,filID': [], 'Field Vals': [4.137079, 3.266032, 19.98699, 11.0, -1.0, -1.0, 0.8042219, 6.37121, 2001.2]}, {'cp_idx': 0.0, 'px': -9.73872, 'py': -8.43293, 'pair_ID': 15.0, 'boundary': 2.0, 'nfil': 0, 'destID,filID': [], 'Field Vals': [8.657229, 7.145235, 41.37377, 15.0, 50.0, 50.0, 0.7326535, 5.40323, 225.1]}, {'cp_idx': 0.0, 'px': -4.05704, 'py': -9.60103, 'pair_ID': 34.0, 'boundary': 2.0, 'nfil': 0, 'destID,filID': [], 'Field Vals': [8.758217, 7.252286, 38.20433, 34.0, 48.0, 48.0, 0.6923507, 4.92437, 372.1]}, {'cp_idx': 0.0, 'px': 8.11413, 'py': 9.88951, 'pair_ID': 39.0, 'boundary': 2.0, 'nfil': 0, 'destID,filID': [], 'Field Vals': [8.83594, 7.335404, 33.73858, 39.0, 67.0, 67.0, 0.6340357, 4.30562, 1986.1]}, {'cp_idx': 0.0, 'px': 9.83801, 'py': -4.27991, 'pair_ID': 17.0, 'boundary': 2.0, 'nfil': 0, 'destID,filID': [], 'Field Vals': [90.02577, -1.0, 126.4486, 17.0, 52.0, 52.0, 0.1523984, 

For some reason this data only has saddles and nodes??

#### Representing filament coordinates in a tabular, easier to see than dictionary way 

In [15]:
# To get a Pandas DataFrame of filaments and their coordinates, we can use the filament_coordinates() method
#help(my_filaments.filament_coordinates)

In [16]:
# Get a DataFrame of filament coordinates and which filament they belong to
my_filaments.filament_coordinates()

px       py  Filament ID
0  -2.44178  6.38983            0
1  -2.49851  6.56155            0
2  -2.67489  6.63576            0
3  -2.56629  6.73880            0
4  -2.49256  6.82773            0
..      ...      ...          ...
13  1.32968  8.85076           72
14  1.27450  8.76351           72
15  1.27510  8.65438           72
16  1.27448  8.54336           72
17  1.30863  8.48716           72

[1949 rows x 3 columns]

#### Represent filament coordinates with their segment pairs 

- include "picket fence" diagram to make it easier visually to see what this is doing

In [17]:
my_filaments.segment_coordinates()

px       py      px2      py2  Filament ID
0  -2.44178  6.38983 -2.49851  6.56155            0
1  -2.49851  6.56155 -2.67489  6.63576            0
2  -2.67489  6.63576 -2.56629  6.73880            0
3  -2.56629  6.73880 -2.49256  6.82773            0
4  -2.49256  6.82773 -2.37843  6.83050            0
..      ...      ...      ...      ...          ...
12  1.34070  8.89817  1.32968  8.85076           72
13  1.32968  8.85076  1.27450  8.76351           72
14  1.27450  8.76351  1.27510  8.65438           72
15  1.27510  8.65438  1.27448  8.54336           72
16  1.27448  8.54336  1.30863  8.48716           72

[1876 rows x 5 columns]

#### Obtaining filament lengths

- from now on, some methods such as this one utilize the tabular represented data (DataFrame) to make calculations, especially using the segment_coordinates() method to calculate the lengths of filaments. However, because all of this is modular, you *DO NOT* need to actually call Filament(path).segment_coordinates() first to use this, the .lengths() method will call the method on its own. 

- more on how the calculation of lengths is executed (in a step-by-step process) can be seen in the **Test-Lengths.ipynb** notebook

In [18]:
help(Filament.lengths)

Help on function lengths in module filament:

lengths(self, DataFrame=True)
    Calculates the lengths of each (half) filament based on the sub-segments of each unique Filament ID.
    Gives option of returning DataFrame with filament segments, IDs and lengths or just the lengths corresponding to each unique Filament ID.

    Parameters:
    DataFrame (bool): Determines whether DataFrame of filament segments, IDs and lengths will be returned. Set to False to return array instead.

    Returns:
    segments (Pandas.DataFrame): DataFrame of Filament segments, IDs and lengths.
        or
    filament_lengths (array-like): Array of lengths correspinding to each unique Filament ID.



In [19]:
# We can obtain the lengths and add them back to the DataFrame for tabular representation
my_filaments.lengths()

px       py      px2      py2  Filament ID  Filament Length
0  -2.44178  6.38983 -2.49851  6.56155            0       326.289413
1  -2.49851  6.56155 -2.67489  6.63576            0       326.289413
2  -2.67489  6.63576 -2.56629  6.73880            0       326.289413
3  -2.56629  6.73880 -2.49256  6.82773            0       326.289413
4  -2.49256  6.82773 -2.37843  6.83050            0       326.289413
..      ...      ...      ...      ...          ...              ...
12  1.34070  8.89817  1.32968  8.85076           72       191.763350
13  1.32968  8.85076  1.27450  8.76351           72       191.763350
14  1.27450  8.76351  1.27510  8.65438           72       191.763350
15  1.27510  8.65438  1.27448  8.54336           72       191.763350
16  1.27448  8.54336  1.30863  8.48716           72       191.763350

[1876 rows x 6 columns]

In [20]:
# Or we can retrieve an array of only the lengths corresponding to each filament ID
my_filaments.lengths(DataFrame=False)

array([3.26289413e+02, 8.58642186e+02, 3.59619165e+02, 2.67764846e+02,
       2.05275172e+02, 1.59943854e+02, 9.51956181e+02, 2.56580522e+02,
       3.23822696e+02, 2.72885387e+02, 1.30268518e+02, 6.07484947e+01,
       7.30939794e+01, 1.52409399e+02, 1.17284297e+02, 2.81936360e+01,
       1.09730593e+02, 1.42665512e+02, 1.54513448e+01, 4.66045194e+02,
       6.42264464e+01, 9.69906998e+00, 1.78990209e+01, 2.05759700e+02,
       2.96569480e+01, 1.14408900e+02, 6.89133470e+01, 1.10669315e+02,
       1.25585684e+02, 8.99466691e+01, 3.59259641e+01, 4.65481572e+02,
       7.76595186e+02, 1.88539246e+01, 5.65883162e+01, 1.25942173e+01,
       1.59699858e+02, 2.48366789e+02, 4.27453862e+02, 9.15065630e+02,
       3.86631298e+02, 9.71569486e+02, 4.58282159e+02, 2.65333905e+01,
       2.56962566e+02, 5.05711438e+02, 1.89121568e+02, 7.03218315e+02,
       4.05712016e+02, 2.50299322e+02, 5.54984630e+01, 4.05043614e+01,
       2.29455678e+02, 1.72517505e+02, 5.17677169e+02, 2.63252497e+00,
      

In [21]:
# Notice that these are only the unique lengths, so naturally the array of values will be smaller than the filament coordinates DataFrame
my_filaments.lengths(DataFrame=False).shape

(73,)

In [22]:
fils1 = my_filaments.filament_dict['filaments']

In [23]:
type(fils1)

list

In [24]:
len(fils1)

73

In [25]:
filindex=np.arange(0,len(fils1))

In [26]:
filindex

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72])

In [27]:
fils.plot_2D(filindex,fils1)

TypeError: only integer scalar arrays can be converted to a scalar index